### ISSUE TITLE
Slideshow won't advance

### ISSUE THREAD

**Issue by jestermagin** [blaise-io/media-carousel#1]
The Media-Carousel registers multiple images at the top such as "1/10" but only shows the first image and doesn't advance manually or automatically.  

Verified same behavior on several web pages of different media. 

Running Mac OS 10.12.6 Sierra and Firefox Quantum ver 57.0

**Comment by blaise-io** [comment]
Hi @jestermagin, thanks for reporting this. 

Unfortunately, I cannot reproduce this issue. Can you please help me figure out what it could be?

 - Can you verify that a webpage with mostly supported image hosts like https://www.reddit.com/r/CatGifs/ shows (nearly) all images?
 - Can you provide me one or more URLs where this is happening? 
 - Can you verify this is also happening when you disable other privacy/security/adblock addons that block or modify content?

**Comment by blaise-io** [comment]
Cannot reproduce, no reply from OP.
