### ISSUE TITLE
tumblr archive view?

### ISSUE THREAD

**Issue by ultima369** [blaise-io/media-carousel#2]
Hi, love Media Carousel, but im wondering, is there a way to make it work with people's archives?

for instance tumblr, when youre in someones blog and click on their archive, Media Carousel comes back with error:

"The page at: moz-extention://......-......-... says:
No supported media found on this page."

im using firefox, windows 10 64bit

**Comment by blaise-io** [comment]
I could make it work, but it would only display the full-size version of the thumbnail for each post. I cannot easily display all images that may be in the post. Would that still be useful to you?

**Comment by ultima369** [comment]
Oh, yeah absolutely. That would absolutely work and would be perfect. Thank
you so much and again, really enjoy your work!

**Comment by blaise-io** [comment]
@ultima369 [tumblr archive view support has landed in 1.1.0](https://addons.mozilla.org/en-US/firefox/addon/media-carousel/versions/)
